package edu.kit.cm.kitcampusguide.ws.poi.soap;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.servlet.http.HttpServletRequest;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.handler.MessageContext;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import edu.kit.tm.cm.kitcampusguide.poiservice.ExecuteFault;
import edu.kit.tm.cm.kitcampusguide.poiservice.ExecuteRequestComplexType;
import edu.kit.tm.cm.kitcampusguide.poiservice.ExecuteResponseComplexType;
import edu.kit.tm.cm.kitcampusguide.poiservice.PoiService;

/**
 * This class was generated by Apache CXF 2.4.1 2011-09-21T11:37:18.173+02:00
 * Generated source version: 2.4.1
 * 
 */

@WebService(serviceName = "PoiService", portName = "PoiServiceSOAP", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", wsdlLocation = "http://www.example.org/?wsdl", endpointInterface = "edu.kit.cm.kitcampusguide.ws.poi.PoiService")
@Transactional
public class PoiServiceImpl extends SpringBeanAutowiringSupport implements PoiService {

    private final Logger log = Logger.getLogger(PoiServiceImpl.class.getName());

    @Resource
    private WebServiceContext context;

    @Autowired
    private PoiService facade;

    public PoiServiceImpl() {
        super();
        // constructor for auto wiring
    }

    public PoiServiceImpl(PoiService facade) {
        super();
        this.facade = facade;
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * edu.kit.tm.cm.kitcampusguide.poi.service.PoiService#execute(edu.kit.tm
     * .cm.kitcampusguide.poi.service.ExecuteRequestComplexType parameters )*
     */
    public ExecuteResponseComplexType execute(ExecuteRequestComplexType parameters) throws ExecuteFault {
        HttpServletRequest servletContext = (HttpServletRequest) context.getMessageContext().get(
                MessageContext.SERVLET_REQUEST);
        log.debug("Handling Request from " + servletContext.getRemoteAddr());

        return this.facade.execute(parameters);
    }

}
