package edu.kit.cm.kitcampusguide.ws.poi.type;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.586+02:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "CreateFault", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/")
public class CreateFault_Exception extends Exception {
	private static final long serialVersionUID = -2151490410482053396L;

	private edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault createFault;

	public CreateFault_Exception() {
		super();
	}

	public CreateFault_Exception(String message) {
		super(message);
	}

	public CreateFault_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public CreateFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault createFault) {
		super(message);
		this.createFault = createFault;
	}

	public CreateFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault createFault,
			Throwable cause) {
		super(message, cause);
		this.createFault = createFault;
	}

	public edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault getFaultInfo() {
		return this.createFault;
	}
}
