package edu.kit.cm.kitcampusguide.ws.poi.type;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.565+02:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "DeleteFault", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/")
public class DeleteFault_Exception extends Exception {
	private static final long serialVersionUID = -9045760045747390436L;

	private edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault deleteFault;

	public DeleteFault_Exception() {
		super();
	}

	public DeleteFault_Exception(String message) {
		super(message);
	}

	public DeleteFault_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public DeleteFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault deleteFault) {
		super(message);
		this.deleteFault = deleteFault;
	}

	public DeleteFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault deleteFault,
			Throwable cause) {
		super(message, cause);
		this.deleteFault = deleteFault;
	}

	public edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault getFaultInfo() {
		return this.deleteFault;
	}
}
