/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.kit.cm.kitcampusguide.ws.poi.soap;

import javax.jws.WebService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import edu.kit.cm.kitcampusguide.ws.poi.PoiService;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateRequest;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.605+02:00
 * Generated source version: 2.4.1
 * 
 */

@WebService(serviceName = "PoiService", portName = "PoiServiceSOAP", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", wsdlLocation = "http://www.example.org/?wsdl", endpointInterface = "edu.kit.cm.kitcampusguide.ws.poi.PoiService")
@Transactional(readOnly = true)
public class PoiServiceImpl extends SpringBeanAutowiringSupport implements PoiService {

	@Autowired
	private PoiService facade;

	public PoiServiceImpl() {
		// constructor for auto wiring
	}

	public PoiServiceImpl(PoiService facade) {
		this.facade = facade;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#update(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.UpdateRequest parameters )*
	 */
	@Override
	@Transactional
	public edu.kit.cm.kitcampusguide.ws.poi.type.UpdateResponse update(UpdateRequest parameters)
			throws UpdateFault_Exception {

		return this.facade.update(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#delete(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.DeleteRequest parameters )*
	 */
	@Override
	@Transactional
	public edu.kit.cm.kitcampusguide.ws.poi.type.DeleteResponse delete(DeleteRequest parameters)
			throws DeleteFault_Exception {

		return this.facade.delete(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#select(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.SelectRequest parameters )*
	 */
	@Override
	public edu.kit.cm.kitcampusguide.ws.poi.type.SelectResponse select(SelectRequest parameters)
			throws SelectFault_Exception {

		return this.facade.select(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#create(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.CreateRequest parameters )*
	 */
	@Override
	@Transactional
	public edu.kit.cm.kitcampusguide.ws.poi.type.CreateResponse create(CreateRequest parameters)
			throws CreateFault_Exception {

		return this.facade.create(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#read(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.ReadRequest parameters )*
	 */
	@Override
	public edu.kit.cm.kitcampusguide.ws.poi.type.ReadResponse read(ReadRequest parameters) throws ReadFault_Exception {

		return this.facade.read(parameters);
	}

}
