package edu.kit.cm.kitcampusguide.ws.poi.type;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.519+02:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "UpdateFault", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/")
public class UpdateFault_Exception extends Exception {
	private static final long serialVersionUID = 7511440100495391739L;

	private edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault updateFault;

	public UpdateFault_Exception() {
		super();
	}

	public UpdateFault_Exception(String message) {
		super(message);
	}

	public UpdateFault_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public UpdateFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault updateFault) {
		super(message);
		this.updateFault = updateFault;
	}

	public UpdateFault_Exception(String message, edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault updateFault,
			Throwable cause) {
		super(message, cause);
		this.updateFault = updateFault;
	}

	public edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault getFaultInfo() {
		return this.updateFault;
	}
}
