/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.kit.cm.kitcampusguide.ws.poi.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import edu.kit.cm.kitcampusguide.ws.poi.PoiService;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateRequest;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.605+02:00
 * Generated source version: 2.4.1
 * 
 */

@WebService(serviceName = "PoiService", portName = "PoiServiceSOAP", endpointInterface = "edu.kit.cm.kitcampusguide.ws.poi.PoiService")
@Transactional
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public class PoiServiceImpl extends SpringBeanAutowiringSupport implements PoiService {

	@Autowired
	private PoiService facade;

	public PoiServiceImpl() {
		super();
		// constructor for auto wiring
	}

	public PoiServiceImpl(PoiService facade) {
		super();
		this.facade = facade;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#update(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.UpdateRequest parameters )*
	 */
	@WebResult(name = "UpdateResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Update", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Update")
	public edu.kit.cm.kitcampusguide.ws.poi.type.UpdateResponse update(
			@WebParam(partName = "parameters", name = "UpdateRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") UpdateRequest parameters)
			throws UpdateFault_Exception {

		return this.facade.update(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#delete(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.DeleteRequest parameters )*
	 */
	@WebResult(name = "DeleteResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Delete", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Delete")
	public edu.kit.cm.kitcampusguide.ws.poi.type.DeleteResponse delete(
			@WebParam(partName = "parameters", name = "DeleteRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") DeleteRequest parameters)
			throws DeleteFault_Exception {

		return this.facade.delete(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#select(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.SelectRequest parameters )*
	 */@WebResult(name = "SelectResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Select", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Select")
	public edu.kit.cm.kitcampusguide.ws.poi.type.SelectResponse select(
			@WebParam(partName = "parameters", name = "SelectRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") SelectRequest parameters)
			throws SelectFault_Exception {

		return this.facade.select(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#create(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.CreateRequest parameters )*
	 */
	@WebResult(name = "CreateResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Create", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Create")
	public edu.kit.cm.kitcampusguide.ws.poi.type.CreateResponse create(
			@WebParam(partName = "parameters", name = "CreateRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") CreateRequest parameters)
			throws CreateFault_Exception {

		return this.facade.create(parameters);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see edu.kit.cm.kitcampusguide.ws.poi.PoiService#read(edu.kit.tm.cm.
	 * kitcampusguide.ws.poi.ReadRequest parameters )*
	 */
	@WebResult(name = "ReadResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Read", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Read")
	public edu.kit.cm.kitcampusguide.ws.poi.type.ReadResponse read(
			@WebParam(partName = "parameters", name = "ReadRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") ReadRequest parameters)
			throws ReadFault_Exception {

		return this.facade.read(parameters);
	}

}
