package edu.kit.cm.kitcampusguide.ws.poi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateResponse;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.673+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", name = "PoiService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PoiService {

	@WebResult(name = "UpdateResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Update", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Update")
	public UpdateResponse update(
			@WebParam(partName = "parameters", name = "UpdateRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") UpdateRequest parameters)
			throws UpdateFault_Exception;

	@WebResult(name = "DeleteResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Delete", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Delete")
	public DeleteResponse delete(
			@WebParam(partName = "parameters", name = "DeleteRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") DeleteRequest parameters)
			throws DeleteFault_Exception;

	@WebResult(name = "SelectResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Select", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Select")
	public SelectResponse select(
			@WebParam(partName = "parameters", name = "SelectRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") SelectRequest parameters)
			throws SelectFault_Exception;

	@WebResult(name = "CreateResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Create", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Create")
	public CreateResponse create(
			@WebParam(partName = "parameters", name = "CreateRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") CreateRequest parameters)
			throws CreateFault_Exception;

	@WebResult(name = "ReadResponse", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", partName = "parameters")
	@WebMethod(operationName = "Read", action = "http://cm.tm.kit.edu/kitcampusguide/poiservice/Read")
	public ReadResponse read(
			@WebParam(partName = "parameters", name = "ReadRequest", targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/") ReadRequest parameters)
			throws ReadFault_Exception;
}
