package edu.kit.cm.kitcampusguide.ws.poi;

import javax.jws.WebService;

import org.springframework.security.access.prepost.PreAuthorize;

import edu.kit.cm.kitcampusguide.ws.poi.type.CreateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.CreateResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.DeleteResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.ReadResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.SelectResponse;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateFault_Exception;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateRequest;
import edu.kit.cm.kitcampusguide.ws.poi.type.UpdateResponse;

/**
 * This class was generated by Apache CXF 2.4.1 2011-07-20T19:00:25.673+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://cm.tm.kit.edu/kitcampusguide/poiservice/", name = "PoiService")
public interface PoiService {

	@PreAuthorize("hasRole('RIGHT_UPDATE_POI')")
	public UpdateResponse update(UpdateRequest parameters) throws UpdateFault_Exception;

	@PreAuthorize("hasRole('RIGHT_DELETE_POI')")
	public DeleteResponse delete(DeleteRequest parameters) throws DeleteFault_Exception;

	@PreAuthorize("hasRole('RIGHT_READ_POI')")
	public SelectResponse select(SelectRequest parameters) throws SelectFault_Exception;

	@PreAuthorize("hasRole('RIGHT_CREATE_POI')")
	public CreateResponse create(CreateRequest parameters) throws CreateFault_Exception;

	@PreAuthorize("hasRole('RIGHT_READ_POI')")
	public ReadResponse read(ReadRequest parameters) throws ReadFault_Exception;
}
